config/routes.rb
D3MarketPlace::Application.routes.draw do
  get "profiles/show"

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :shouts
  get 'shoutbox', to: 'shouts#index', as: :shoutbox
root :to => "shouts#index"

get '/:battle_tag_name', to: 'profiles#show'

end

app/models/shout.rb
class Shout < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  :battle_tag_name, :battle_tag_code
  # attr_accessible :title, :body


  has_many :shouts

  def full_battle_tag
  		battle_tag_name + "#" +battle_tag_code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_battle_tag_name(params[:battle_tag_name])
  	if @user
  		@shouts = @user.shouts.all
  		render action: :show

  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  # GET /shouts
  # GET /shouts.json
  def index
    @shouts = Shout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shouts }
    end
  end

  # GET /shouts/1
  # GET /shouts/1.json
  def show
    @shout = Shout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shout }
    end
  end

  # GET /shouts/new
  # GET /shouts/new.json
  def new
    @shout = Shout.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shout }
    end
  end

  # GET /shouts/1/edit
  def edit
    @shout = Shout.find(params[:id])
  end

  # POST /shouts
  # POST /shouts.json
  def create
    @shout = Shout.new(params[:shout])
    @shout.user_id = current_user.id

    respond_to do |format|
      if @shout.save
        format.html { redirect_to @shout, notice: 'Shout was successfully created.' }
        format.json { render json: @shout, status: :created, location: @shout }
      else
        format.html { render action: "new" }
        format.json { render json: @shout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shouts/1
  # PUT /shouts/1.json
  def update
    @shout = Shout.find(params[:id])

    respond_to do |format|
      if @shout.update_attributes(params[:shout])
        format.html { redirect_to @shout, notice: 'Shout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shouts/1
  # DELETE /shouts/1.json
  def destroy
    @shout = Shout.find(params[:id])
    @shout.destroy

    respond_to do |format|
      format.html { redirect_to shouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else
			""
		end
	end


	
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3MarketPlace</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="masthead">
		<%= image_tag "d3marketplace-header.jpg" %>
	</div>
	<div class="navbar navbar-static-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand" href="#"> 
					D3MarketPlace </a>
					<ul class="nav">
						<li><%= link_to "ShoutBox", shoutbox_path %>
						</li>
							<form class="navbar-search pull-right">
							<input type="text" class="search-query" placeholder="Search" >
						</form>
					</ul>

					<ul class="nav pull-right">

						<% if user_signed_in? %>

						<li> <%= link_to current_user.full_battle_tag, edit_user_registration_path %>
						</li>
						<li><%= link_to "Log out", logout_path %>
						</li>
						<% else %>
						<li><%= link_to "Register", register_path %>
						</li>
						<li><%= link_to "Log in", login_path %>
						</li>
						<% end %>
				</ul>
				</div>
		</div>
	</div>
<div class="container">
	<% flash.each do |type, message| %>
	<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">x</button>
				<%= message %>
				</div>
	<% end %>
			

		
<%= yield %>
</div>
</body>
</html>

app/views/profiles/show.html.erb
<head>
	


</head>
<div class="page-header">
	<h1><%= @user.full_battle_tag %></h1>
</div>

<%  @career = D3api::Career.new(:eu, @user.battle_tag_name, @user.battle_tag_code) %>
<ul class="nav nav-tabs" id="myTab">
	<li class="active"><a href="#shouts" data-toggle="tab">Shouts</a></li>
	<li><a href="#heroes" data-toggle="tab">Heroes</a></li>
	<li><a href="#stats" data-toggle="tab">Stats</a></li>
</ul>

<div class="tab-content">
	<div class="tab-pane active" id="shouts"><% if @shouts %>
		<% @shouts.each do |shout| %>
		<div class="well">

			<%= shout.content %>

			<%= link_to time_ago_in_words(shout.created_at), shout_path(shout) %> ago
		</div>
		<% end %>
		<% end %>
	</div>

	<div class="tab-pane" id="heroes">
		<div class="hero-tab-content">
			<div class="well">
				<p1>Heroes: </p1>
				<hr>

				
						
		

				<div id="tablediv">
					<table class="table table-hover">


						<thead> 
							<tr>
								<th>Name</th>
								<th>Class</th>
								<th>Level</th>
							</tr>
						</thead>
						<% heroes = @career.heroes[0] %>
						<% for i in 0 .. @career.heroes.size-1 %>
						<% heroes[i] = @career.heroes[i] %>
						<% names = heroes['name'] %>
						<% classes = heroes['class'] %>
						<% levels = heroes['level'] %>
						<tbody>
							<tr>
								<td> <%=names %> </td>
								<td> <%=classes %> </td>
								<td> <%=levels %></td>
								<% end %>
							</tr>
						</tbody>

					</table>
				</div>

			</br></br>

			

		</div>
	</div>
</div>

<div class="tab-pane" id="stats">
	<div class="well">
		<p1>Stats: </p1>
		<hr>
		<b>Last played: </b> <%= time_ago_in_words(@career.last_updated) %> ago </br>
		<b>Monster Kills:</b> <%= @career.monster_kills %> </br>
		<b>Elite Kills: </b> <%= @career.elite_kills %></br>
		<b>Hardcore Kills: </b> <%= @career.hardcore_monster_kills %> </br>
		<%=  %>
	</div>
</div>

</div>

app/views/shouts/_form.html.erb
<%= simple_form_for(@shout, html: {class: "well"}) do |f| %>
  <% if @shout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shout.errors.count, "error") %> prohibited this shout from being saved:</h2>

      <ul>
      <% @shout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= f.input :content %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shouts/edit.html.erb
<h1>Editing shout</h1>

<%= render 'form' %>

<%= link_to 'Show', @shout %> |
<%= link_to 'Back', shouts_path %>

app/views/shouts/index.html.erb
<div class="page-header">
	<h1>ShoutBox</h1>
</div>

<% if user_signed_in? %>
<%= link_to "Create new shout", new_shout_path, class: "btn" %>
<% end %>

<% @shouts.each do |shout| %>
<div class="shout">
	<div class="row">
		<div class="span1">
			<!-- DUMMY AVATAR -->
			<%= image_tag "dummy-avatar.png" %>
		</div>
		<div class="span7">
			<strong><%= link_to shout.user.full_battle_tag, shout.user.battle_tag_name %></strong>
			<p><%= shout.content %> </p>


			<div class="meta">
				<%= link_to time_ago_in_words(shout.created_at) + " ago", shout %>
				<span class="admin">
					| <%= link_to 'Edit', edit_shout_path(shout) %> |
					<%= link_to 'Delete', shout, method: :delete, data: { confirm: "are you sure?"} %>
				</div>
			</div>
		</div>
	</div>

	<% end %>

app/views/shouts/new.html.erb
<h1>New shout</h1>

<%= render 'form' %>

<%= link_to 'Back', shouts_path %>

app/views/shouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shout.user.full_battle_tag %>
</p>

<p>
  <b>Content:</b>
  <%= @shout.content %>
</p>


<%= link_to 'Edit', edit_shout_path(@shout) %> |
<%= link_to 'Back', shouts_path %>